### ISSUE TITLE
hi what is userIF? and why i can't login using it?

### ISSUE THREAD

**Issue by minanagehsalalma** [LXGMAX/telecomadmin#1]
https://forum.antichat.ru/attachments/9046/

also why i can't login using these
https://preview.redd.it/lcqvs7tk0ii41.png?width=367&format=png&auto=webp&s=31bdad8cff3c7e6abfc49cdac8222b42990271d1

although the enable value = 1
the only difference i see is the app ID What would that be? Why are they there?

**Comment by LXGMAX** [comment]
I don't know all values in the table,it was known by the manufacturer.

**Comment by minanagehsalalma** [comment]
> it was known by the manufacturer.

I have asked the provider but they didn't know .... as they aren't the manufacturer 
.... can you contact them in case if you bought it directly from them ?

**Comment by LXGMAX** [comment]
I have no way to contact,but it is a ZET's device,maybe you could find them.

**Comment by minanagehsalalma** [comment]
> I have no way to contact

Nah you have.... if you bought it directly from them not an isp as in my case ... you can ask them (zte support) for help .. other than that they won't help you.
